name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]  # Change "main" to your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest  # Adjust OS if needed
    steps:
      - uses: actions/checkout@v3

      - uses: huggingface/hugging-push@v3
        with:
          token: ${{ secrets.HF_HUB_TOKEN }}
          repo_url: https://huggingface.co/<username>/<model-repo>  # Replace with your Hub URL (if applicable)
          commit_message: "Deploy from branch ${{ github.ref }}"  # Optional commit message
