name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]  # Change "main" to your branch name if different

jobs:
  deploy:
    runs-on: windows-latest  # Adjust OS if needed
    steps:
      - uses: actions/checkout@v3

      - uses: huggingface/hugging-push@v4
        with:
          token: ${{ secrets.HF_HUB_TOKEN }}
          commit_message: "Deploy from branch ${{ github.ref }}"  # Optional commit message
